sntbr.front/Models/Widgets/AuthWidget.cs
using System;

namespace sntbr.front.Models.Widgets
{
	public class AuthWidget : IWidgetViewModel
	{
		public string Name { get; private set; }

		public string PartialView
		{
			get { return "~/Views/Widgets/AuthWidget.cshtml"; }
		}

		public AuthWidget(string name)
		{
			if (string.IsNullOrEmpty(name))
				throw new ArgumentNullException("name");
			Name = name;
		}
	}
}

sntbr.front/Models/Widgets/AuthWidgetLogin.cs
using System;
using System.Collections.Generic;
using sntbr.front.Models.Account.Partials;

namespace sntbr.front.Models.Widgets
{
	public class AuthWidgetLogin : IWidgetViewModel
	{
		public IEnumerable<ProviderPartial> Providers { get; private set; }
		public string ReturnUrl { get; private set; }

		public string PartialView
		{
			get { return "~/Views/Widgets/AuthWidgetLogin.cshtml"; }
		}

		public AuthWidgetLogin(IEnumerable<ProviderPartial> providers, string returnUrl)
		{
			if (providers == null)
				throw new ArgumentNullException("providers");
			Providers = providers;
			ReturnUrl = returnUrl;
		}
	}
}

sntbr.front/Models/Widgets/GisMeteoWidget.cs
namespace sntbr.front.Models.Widgets
{
	public class GisMeteoWidget : IWidgetViewModel
	{
		public string City { get; private set; }

		public string Hash { get; private set; }

		public string PartialView
		{
			get { return "~/Views/Widgets/GisMeteoWidget.cshtml"; }
		}

		public GisMeteoWidget(string city, string hash)
		{
			City = city;
			Hash = hash;
		}
	}
}

sntbr.front/Models/Widgets/WidgetFactory.cs
using System.Web;
using Microsoft.Owin.Security;
using sntbr.domain.Housing;
using sntbr.domain.Housing.Repositories;
using sntbr.front.Models.Common;

namespace sntbr.front.Models.Widgets
{
	public class WidgetFactory : IPageService
	{
		public WidgetFactory(IAuthenticationManager authenticationManager, ResidentRepository residentRepository)
		{
			_authManager = authenticationManager;
			_residentRepo = residentRepository;
		}

		public GisMeteoWidget GisMeteoWidget()
		{
			return new GisMeteoWidget("4369", "SeYST1CgdU7VcH");
		}

		public IWidgetViewModel AuthWidget()
		{
			if (!_authManager.User.Identity.IsAuthenticated)
			{
				var provs = _authManager.ProviderPartials();
				return new AuthWidgetLogin(provs, HttpContext.Current.Request.Url.ToString());
			}

			string userName = _authManager.User.Identity.Name;
			Resident resident = _residentRepo.GetByUserName(userName);
			return new AuthWidget(resident == null ? userName : resident.FirstName ?? resident.LastName);
		}

		private readonly IAuthenticationManager _authManager;
		private readonly ResidentRepository _residentRepo;
	}
}

sntbr.front/Controllers/ProfileController.cs
using System.Web.Mvc;
using sntbr.front.Models.Common;
using sntbr.front.Models.Profile;
using sntbr.front.Models.Profile.Pages;
using sntbr.front.Models.Profile.Partials;

namespace sntbr.front.Controllers
{
	[Authorize(Roles = SntbrRoles.User)]
	public class ProfileController : Controller
	{
		public ProfileController(ProfilePageFactory pageFactory, ProfileInputService inputService)
		{
			_pageFactory = pageFactory;
			_inputService = inputService;
		}

		public ActionResult Index()
		{
			IndexPage page = _pageFactory.IndexPage(User.Identity.Name);

			return View("~/Views/Profile/Pages/Index.cshtml", page);
		}

		public ActionResult Edit()
		{
			EditPage page = _pageFactory.EditPage(User.Identity.Name);

			return View("~/Views/Profile/Pages/Edit.cshtml", page);
		}

		[HttpPost]
		public ActionResult Edit(ProfileEditModel model)
		{
			if (ModelState.IsValid)
			{
				_inputService.ProcessProfileEdit(User.Identity.Name, model);
				return RedirectToAction("index");
			}

			EditPage page = _pageFactory.EditPage(model);
			return View("~/Views/Profile/Pages/Edit.cshtml", page);
		}

		public ActionResult Site()
		{
			SitePage page = _pageFactory.SitePage(User.Identity.Name);
			if (page == null)
				return RedirectToAction("edit");
			return View("~/Views/Profile/Pages/Site.cshtml", page);
		}

		[HttpPost]
		public ActionResult Site(string action, string site)
		{
			_inputService.ProcessSiteSet(User.Identity.Name, site, action);

			return RedirectToAction("index");
		}

		private readonly ProfilePageFactory _pageFactory;
		private readonly ProfileInputService _inputService;
	}
}

sntbr.front/Views/Widgets/AuthWidget.cshtml
@model sntbr.front.Models.Widgets.AuthWidget
<h2>Садовод @Model.Name</h2>
<p>
	@Html.ActionLink("профиль садовода", "Index", "Profile")
</p>
@using (Html.BeginForm("Logoff", "Account"))
{
	@Html.AntiForgeryToken()
	<button type="submit">выйти</button>
}

sntbr.front/Views/Widgets/AuthWidgetLogin.cshtml
@model sntbr.front.Models.Widgets.AuthWidgetLogin
<h2>Кто Вы?</h2>
<p>
	Представьтесь с помощью
</p>
@foreach (var prov in Model.Providers)
{
	using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = Model.ReturnUrl }))
	{
		@Html.AntiForgeryToken()
		<input type="hidden" id="@prov.AuthenticationType" name="provider" value="@prov.AuthenticationType" />
		<input type="image" title="Войдите с помощью @prov.Caption аккаунта" src="@prov.LogoUrl" />
	}
}

sntbr.front/Views/Widgets/GisMeteoWidget.cshtml
@model sntbr.front.Models.Widgets.GisMeteoWidget
<h2>Погода</h2>
<p></p>
<!-- Gismeteo informer START -->
<link rel="stylesheet" type="text/css" href="http://www.gismeteo.ru/static/css/informer2/gs_informerClient.min.css">
<div id="gsInformerID-@Model.Hash" class="gsInformer" style="width:240px;height:243px">
	<div class="gsIContent">
		<div id="cityLink">
			<a href="http://www.gismeteo.ru/city/daily/@Model.City/" target="_blank">Погода в Домодедово</a>
		</div>
		<div class="gsLinks">
			<table>
				<tr>
					<td>
						<div class="leftCol">
							<a href="http://www.gismeteo.ru" target="_blank">
								<img alt="Gismeteo" title="Gismeteo" src="http://www.gismeteo.ru/static/images/informer2/logo-mini2.png" align="absmiddle" border="0" />
								<span>Gismeteo</span>
							</a>
						</div>
						<div class="rightCol">
							<a href="http://www.gismeteo.ru/city/weekly/@Model.City/" target="_blank">Прогноз на 2 недели</a>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<script src="http://www.gismeteo.ru/ajax/getInformer/?hash=@Model.Hash" type="text/javascript"></script>
<!-- Gismeteo informer END -->